name: Build godot project
on: [push]
jobs:
  Install-dependencies:
    runs-on: ubuntu-latest
    env:
      GODOT: Godot_v3.3-stable_linux_headless.64

    steps:
      - run: echo "Configure ubuntu"
      - run: sudo apt update && sudo apt upgrade --yes --force-yes
      - run: sudo apt install unzip curl git --yes --force-yes
      - run: locale
      - run: echo "Install godot dependencies"
      - run: sudo apt install xvfb libxcursor1 libxinerama1 libxrandr2 libxi6 libasound2 libpulse0 libgl1-mesa-glx --yes --force-yes
      - run: echo "Download godot version ${GODOT}"
      - run: curl https://downloads.tuxfamily.org/godotengine/3.3/${GODOT}.zip > /tmp/${GODOT}.zip
      - run: unzip -p /tmp/${GODOT}.zip > /tmp/${GODOT} && chmod +x /tmp/${GODOT}

      - name: Check out repository code
        uses: actions/checkout@v2

      - run: "export the project"
      - run: mkdir -p _build
      - run: /tmp/${GODOT} --export HTML5 _build/LD48-$(git rev-parse --short "$GITHUB_SHA").html

